### ISSUE TITLE
Support numbers

### ISSUE THREAD

**Issue by lishaduck** [AntonioVdlC/html-template-tag#199]
I have quite a few numbers that I need to inject into a template. It would be considerably less verbose to pass them in than to call .toString on all of them.

Would it be possible to change this: 
https://github.com/AntonioVdlC/html-template-tag/blob/c42a010bd2d99cb97c83ee075c6266ea6179fdf1/src/index.ts#L8

to 

```ts
 ...substs: Array<string | string[] | number> 
```

? (I can think of a reason to support `number[]`, so I think you could skip that).

P.S: Thanks for the package! It provides better intellisense, formatting, and security—all in one! It's fantastic.

**Comment by lishaduck** [comment]
I will cite typescript-eslint/typescript-eslint#9311 as the reasoning against this sort of change. I'll need to think on this.

**Comment by AntonioVdlC** [comment]
Thanks for the suggestion!

As you pointed out, it's probably trivial to stringify integers within the package itself (and currently quite verbose on the customer's side), but not so clearcut for floats (e.g. how many decimal points?). 

In general, I'd prefer that customers of this package decide how they want to stringify other types, instead of trying to do that in the package itself.
